services:
  bot:
    build: .
    container_name: max-autopost-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9154:9154"
    volumes:
      - ./.env:/app/.env:ro
      - ./channels.json:/app/channels.json:ro
